### PR TITLE
`client/server` path must exist

### LINKED ISSUE #24: Attribute 'outDir' does not exist
I simply do what README says and get:

```
Attribute 'outDir' does not exist ('/home/cblp/dev/vscode-ghc-mod/server/../client/server').: Error: Attribute 'outDir' does not exist ('/home/cblp/dev/vscode-ghc-mod/server/../client/server').
    at Object.C [as create] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:34:19570)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:105:21677
    at Object.m [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:8153)
    at Object.B.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:11658)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12979)
    at i.Class.define._chainedError (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12338)
    at i (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10161)
    at i.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:13788)
    at Object.P.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10230)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12979)
```

### PR DESCRIPTION
**Pull request by cblp**
fixes #24

### CODE REVIEW

**Comment by hoovercj** [comment]
I don't believe this is the correct solution as it will add the compiled server to the git repo. The correct solution is to build it locally on its own (and improve the README) and/or to improve the build scripts.

**Comment by cblp** [comment]
Okay, I don't understand what "compiled server" is. I'm looking forward clearer instructions.

**Comment by hoovercj** [comment]
This is a typescript project so it must be compiled to JavaScript. The server folder has a build script that will compile it into the out/ directory in the client folder so that it may be used by the client.

Opening the server folder in vs code and using the build command from the command palette (maybe also ctrl+shift+B) should do this.

**Comment by cblp** [comment]
Is it the simplest way? Is there a command like `npm build`?

**Comment by cblp** [comment]
Looks like

```
$ cd server
$ npm install
$ tsc
```

do the job.

**Comment by cblp** [comment]
`tsc` without arguments should build a project according to http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by cblp** [comment]
No sense.

**Pull request closed without merging**
