### PR TITLE
Correctly handle pragma comments

### LINKED ISSUE #48: Pragmas are not filtered, crashing ghc-mod on hover.
Hovering opening part of pragma like this: `{-# LANGUAGE NoMonomorphismRestriction #-}`
results in error message `ghc-mod crashed on command info hello.hs -#`
Nested comments check in /server/src/utils/document.ts should be extended to include this case.

### PR DESCRIPTION
**Pull request by danstiner**
Fixes #48

### CODE REVIEW

**Comment by hoovercj** [comment]
This does in fact fix the pragma issue but doesn't fix the issue with comments.

If you hover over `---` it will still throw an exception. How can we be more general such that only valid symbols make it out?

**Comment by danstiner** [comment]
Excellent call, used a regex to cover such cases as well.

Also rebased on master

**Comment by hoovercj** [comment]
Am I correct that your added regex will match only strings of `-`? Does the `$` at the end mean "end of string"?

Will it match `---A`, for example? Because that makes ghc-mod crash.

Also, I can see that `->-` and `-.` will fail wheras `-A-` will not. Basically I think anything that starts with `-` and isn't immediately followed by a letter or `>` or ends with `}` will cause  an exception.

Test cases to add:
-[ ] `->-`
-[ ] `-.`
-[ ] `--->`
-[ ] `---A`

I appreciate your contribution and it should be easy to build on, so let me know if you'd like me to merge your change and then fix these edge cases myself.

**Comment by danstiner** [comment]
It does correctly handle comments as far as I can tell, e.g. ```---A``` is a comment and hovering over the dashes gives an empty string.

However you found some great other cases which are valid operator symbols, but crash ghc-mod. I guess anything starting with a dash should be filtered out in ```isBlacklisted```?

**Comment by danstiner** [comment]
Added the blacklisting. Seems pretty broad, but ghc-mod is crashing for them so I guess that's the way it has to be until we get a better back-end.

**Comment by danstiner** [comment]
Force pushed an amended commit to fix tslint complaint

**Comment by hoovercj** [comment]
Thanks for the contribution! Hopefully these crashes are gone for good :-)

**Pull request merged**
